sudo: false

addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - texlive-fonts-extra
    - texlive-science
    - texlive-bibtex-extra
    - biblatex
    - latexmk

script:
  - mkdir -p out out/include out/chapters
  - latexmk -pdf -cd -outdir=../out -jobname=hierarchical_runtime_verification -interaction=nonstopmode -file-line-error ./src/main